name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@v5

      - name: Build
        run: cargo build --verbose

      - name: Install cargo-hack
        run: cargo install cargo-hack

      - name: Build environment combinations
        run: cargo hack build --feature-powerset

      - name: Test environment combinations
        run: cargo hack test --feature-powerset

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cargo install cargo-hack
      - run: cargo hack clippy --feature-powerset --all-targets -- -D warnings

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cargo doc --all-features --no-deps

  roots:
    uses: ./.github/workflows/roots.yml
